apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: driv/buildpack-playground-golang-api:b6.20240507.080031 # {"$imagepolicy": "flux-system:buildpack-playground-golang-api"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4444
              protocol: TCP
              