---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: buildpack-playground-golang-api
  namespace: flux-system
spec:
  image: driv/buildpack-playground-golang-api
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: buildpack-playground-golang-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: buildpack-playground-golang-api
  filterTags:
    pattern: '^b.*'
  policy:
    alphabetical:
      order: asc
