name: Conftest Validate ingress yaml

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    container:
      image: openpolicyagent/conftest:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Policy Checks
        run: |
          conftest test kubernetes/*.yaml --policy policy/